version: '3'
services:
  nginx:
    build: nginx
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./application:/var/www/html
    networks:
      - alzort
    environment:
      APP_ENV: ${APP_ENV}
  php:
    build: php
    volumes:
      - ./application:/var/www/html
    networks:
      - alzort
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - alzort
  redis:
    image: redis:alpine
    volumes:
      - redisdata:/data
    networks:
      - alzort
networks:
  alzort:
    driver: "bridge"
volumes:
  redisdata:
    driver: "local"
  mysqldata:
    driver: "local"