version: '3'
services:
  nginx:
    build: nginx
    ports:
      - "8080:80"
    volumes:
      - ./application:/var/www/html
    networks:
      - alzort
  php:
    build: php
    volumes:
      - ./application:/var/www/html
    networks:
      - alzort
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: alzort
      MYSQL_USER: alzort
      MYSQL_PASSWORD: secret
    ports:
      - "33060:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - alzort
  redis:
    image: redis:alpine
    volumes:
      - redisdata:/data
    networks:
      - alzort
networks:
  alzort:
    driver: "bridge"
volumes:
  redisdata:
    driver: "local"
  mysqldata:
    driver: "local"